version: "3"

services:
  step3_mysql:
    container_name: step3_mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "ssar"
      MYSQL_PASSWORD: "ssar1234"
      MYSQL_DATABASE: "blogdb"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  step3_app:
    container_name: step3_backend
    image: openjdk:11-jdk-slim
    environment:
      RDS_HOSTNAME: "localhost"
      RDS_PORT: 3306
      RDS_USERNAME: "ssar"
      RDS_PASSWORD: "ssar1234"
      RDS_DB_NAME: "blogdb"
    ports:
      - "8080:8080"
    depends_on:
      - step3_mysql
    working_dir: /app
    command:
        - bash
        - -c
        - >
          apt-get update;
          apt-get install git -y;
          git clone https://github.com/111coding/blog-user-step15.git;
          cd blog-user-step15;
          chmod +x gradlew;
          ./gradlew build;
          chmod +x build/libs/*.jar;
          java -jar -Dspring.profiles.active=docker build/libs/*.jar;
